question_data = [
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "The Atlantic Ocean is the largest ocean on Earth.", "answer": "False"},
    {"text": "Humans share 50% of their DNA with bananas.", "answer": "True"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "Venus is the hottest planet in the solar system.", "answer": "True"},
    {"text": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
    {"text": "The Nile is the longest river in the world.", "answer": "False"},
    {"text": "A group of crows is called a murder.", "answer": "True"},
    {"text": "The human skeleton is made up of 206 bones.", "answer": "True"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "Water boils at 100 degrees Celsius.", "answer": "True"},
    {"text": "The Eiffel Tower can grow more than six inches during summer.", "answer": "True"},
    {"text": "The capital city of Canada is Toronto.", "answer": "False"},
    {"text": "Polar bears have black skin under their white fur.", "answer": "True"},
    {"text": "Coffee is made from berries.", "answer": "True"},
    {"text": "Humans can breathe and swallow at the same time.", "answer": "False"},
    {"text": "The moon is larger than Pluto.", "answer": "True"},
    {"text": "Goldfish only have a memory of three seconds.", "answer": "False"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "A year on Mars is longer than a year on Earth.", "answer": "True"},
    {"text": "Walt Disney was the creator of Mickey Mouse.", "answer": "True"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Albert Einstein failed math in school.", "answer": "False"},
    {"text": "Dogs sweat through their tongues.", "answer": "False"},
    {"text": "An ostrich's eye is bigger than its brain.", "answer": "True"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "The sun is a star.", "answer": "True"},
    {"text": "Spiders are insects.", "answer": "False"},
    {"text": "The Pacific Ocean is deeper than the Atlantic Ocean.", "answer": "True"},
    {"text": "There are 365 days in a leap year.", "answer": "False"},
    {"text": "The fastest land animal is the cheetah.", "answer": "True"},
    {"text": "Tomatoes are a type of vegetable.", "answer": "False"},
    {"text": "Hawaii is the only U.S. state that grows coffee.", "answer": "True"},
    {"text": "The shortest war in history lasted 38 minutes.", "answer": "True"},
    {"text": "Sound travels faster in water than in air.", "answer": "True"},
    {"text": "The blue whale is the largest animal to have ever lived.", "answer": "True"},
    {"text": "Slugs have four noses.", "answer": "True"},
    {"text": "There are more stars in the universe than grains of sand on Earth.", "answer": "True"},
    {"text": "The Earth revolves around the moon.", "answer": "False"},
    {"text": "Koalas sleep up to 22 hours a day.", "answer": "True"},
    {"text": "Venus is the closest planet to the Sun.", "answer": "False"},
    {"text": "The human nose can detect over 1 trillion different scents.", "answer": "True"},
    {"text": "Saturn is the only planet with rings.", "answer": "False"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"text": "The speed of light is faster than the speed of sound.", "answer": "True"},
    {"text": "The heart of a shrimp is located in its head.", "answer": "True"}
]




